create or replace TRANSIENT TABLE FDA.DEV_TS01_DEV003 (
	NAME VARCHAR(40) NOT NULL,
	"Emp_ID" NUMBER(38,0) NOT NULL DEFAULT FDA."DEV_sequence003".NEXTVAL,
	"Gender" VARCHAR(50),
	SALARY NUMBER(18,3),
	DOB DATE NOT NULL,
	primary key ("Emp_ID")
);